discard_position = {x=-11.75,y=2,z=-1.75}
discard_rotation = {x=0, y=0, z=0}
function onload()
    button = {}
    button.position = {0, 0, 0}
    button.rotation = {0, 0, 0}
    button.label = 'Fold hand'
    button.click_function = 'foldHand'
    button.function_owner = self
    button.font_size = 200
    button.width = 1500
    button.height = 300
    self.createButton(button)
end

function foldHand (object, player)
    local cards = Player[player].getHandObjects()
    for i in pairs(cards) do
        cards[i].setRotation(discard_rotation)
        cards[i].flip()
        Wait.time(|| cards[i].setPosition(discard_position,false,false), 0.5)
    end
end