function onload()
  button = {}
  button.position = {0, 0, 0}
  button.rotation = {0, 0, 0}
  button.label = 'Fold hand'
  button.click_function = 'foldHand'
  button.function_owner = self
  button.font_size = 200
  button.width = 1500
  button.height = 300
  self.createButton(button)
end

function foldHand (object, player)
  local cards = Player[player].getHandObjects()
  for i in pairs(cards) do
    cards[i].setRotation(Global.getVar("discard_rotation"))
    cards[i].flip()
    Wait.time(|| cards[i].setPosition(Global.getVar("discard_position"),false,false), 0.5)
  end
end
